# SPDX-License-Identifier: GPL-2.0

#
# Makefile wrapper for Linux kernel 5.10 of Orange Pi 5.
#
# Copyright (c) 2024 Man Hung-Coeng <udc577@126.com>
#

PKG_FILE := ./orange-pi-5.10-rk3588.tar.gz
PKG_URL := https://github.com/orangepi-xunlong/linux-orangepi/archive/refs/heads/orange-pi-5.10-rk3588.tar.gz

include ../default.mk

