# SPDX-License-Identifier: GPL-2.0

#
# Makefile wrapper for Linux kernel 5.10 of Orange Pi 5.
#
# Copyright (c) 2024 Man Hung-Coeng <udc577@126.com>
#

PKG_FILE := ./linux-orangepi-orange-pi-5.10-rk35xx.tar.gz
#PKG_URL := https://github.com/orangepi-xunlong/linux-orangepi/archive/refs/heads/orange-pi-5.10-rk35xx.tar.gz
PKG_URL ?= https://github.com/orangepi-xunlong/linux-orangepi/archive/b03bc7f3661bd8fd41f8ca8011e28acdaeec0a67.tar.gz

include ../default.mk

