PKG_FILE := ./linux-orangepi-41b50f13883873202ee2375ec2f58970941c314a.tar.gz
PKG_URL ?= https://github.com/orangepi-xunlong/linux-orangepi/archive/41b50f13883873202ee2375ec2f58970941c314a.tar.gz
EXT_TARGETS +=
CUSTOM_FILES +=

include ../common.mk
include ../../wrapper.mk

