PKG_FILE := ./linux-orangepi-752c0d0a12fdce201da45852287b48382caa8c0f.tar.gz
PKG_URL ?= https://github.com/orangepi-xunlong/linux-orangepi/archive/752c0d0a12fdce201da45852287b48382caa8c0f.tar.gz
EXT_TARGETS += drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.ko
CUSTOM_FILES += net/mac80211/util.c \
    net/mac80211/main.c \
    net/mac80211/ieee80211_i.h \
    drivers/net/wireless/realtek/rtl8xxxu/Kconfig \
    drivers/net/wireless/realtek/rtl8xxxu/Makefile \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.h \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8188e.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8188f.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8192c.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8192e.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8192f.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8710b.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8723a.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_8723b.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_core.c \
    drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu_regs.h \
    drivers/media/platform/rockchip/cif/capture.c \
    drivers/media/platform/rockchip/cif/hw.c \
    drivers/media/platform/rockchip/cif/hw.h \
    drivers/media/platform/rockchip/cif/dev.c \
    drivers/media/platform/rockchip/cif/dev.h \
    drivers/media/platform/rockchip/cif/mipi-csi2.c \
    drivers/media/platform/rockchip/cif/mipi-csi2.h \
    drivers/media/platform/rockchip/cif/cif-scale.c \
    drivers/media/platform/rockchip/cif/subdev-itf.c \
    drivers/phy/rockchip/phy-rockchip-csi2-dphy-common.h \
    drivers/phy/rockchip/phy-rockchip-samsung-dcphy.c \
    drivers/phy/rockchip/phy-rockchip-samsung-dcphy.h \
    drivers/phy/rockchip/phy-rockchip-csi2-dphy-hw.c \
    drivers/phy/rockchip/phy-rockchip-csi2-dphy.c

include ../common.mk
include ../../wrapper.mk

