# SPDX-License-Identifier: GPL-2.0

#
# Makefile wrapper for Linux kernel 6.1 of Orange Pi 5.
#
# Copyright (c) 2024 Man Hung-Coeng <udc577@126.com>
#

PKG_FILE := ./linux-orangepi-752c0d0a12fdce201da45852287b48382caa8c0f.tar.gz
#PKG_URL := https://github.com/orangepi-xunlong/linux-orangepi/archive/refs/heads/orange-pi-6.1-rk35xx.tar.gz
PKG_URL ?= https://github.com/orangepi-xunlong/linux-orangepi/archive/752c0d0a12fdce201da45852287b48382caa8c0f.tar.gz

include ../default.mk

