PKG_FILE := ./linux-orangepi-b03bc7f3661bd8fd41f8ca8011e28acdaeec0a67.tar.gz
PKG_URL ?= https://github.com/orangepi-xunlong/linux-orangepi/archive/b03bc7f3661bd8fd41f8ca8011e28acdaeec0a67.tar.gz
EXT_TARGETS +=
CUSTOM_FILES +=

include ../common.mk
include ../../wrapper.mk

